stages:
  process_data:
    cmd: python src/training/process_data.py
    deps:
    - data/raw/titanic.csv
    - src/training/process_data.py
    outs:
    - data/processed/pipeline.pkl
    - data/processed/titanic-test.parquet
    - data/processed/titanic-train.parquet
  train_model:
    cmd: python src/training/train.py
    deps:
      - src/training/train.py
      - data/processed/titanic-train.parquet
      - params.yaml
    params:
      - model.processed_data_path
      - model.file_name
      - model.target
      - model.model_path
      - model.model_name
      - model.hyperparameters.space
      - model.hyperparameters.n_folds
      - model.training.max_evals
      - model.training.max_iter
    outs:
      - models/LogisticRegression/model_target_translator.pkl
      - models/LogisticRegression/final_model.pkl

  evaluate_model:
    cmd: python src/training/evaluate.py
    deps:
    - models/LogisticRegression/final_model.pkl
    - models/LogisticRegression/model_target_translator.pkl
    - data/processed/titanic-test.parquet
    - src/training/evaluate.py
    outs:
    - reports/LogisticRegression/evaluation_report.json
